# fly.toml app configuration file generated for itamadev on 2023-06-03T00:52:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itamadev"
primary_region = "ams"

[http_service]
  internal_port = 1313
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
